spring:
  application:
    name: sigra-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # En desarrollo crea/actualiza las tablas automáticamente
    show-sql: true        # Muestra las consultas SQL en consola
    properties:
      hibernate:
        format_sql: true
  #data:
  #  redis:
  #    host: ${REDIS_HOST:localhost}
  #    port: ${REDIS_PORT:6379}

server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}

springdoc:
  swagger-ui:
    path: /swagger-ui.html